export interface ProblemRequirements {
  readsPerSec: number;   // k/s
  writesPerSec: number;  // k/s
  storage: string;
  latencySLA: string;
  users: string;
}

export interface ScoringCriteria {
  description: string;
  componentIds: string[];  // any of these present = criteria met
  points: number;
}

export interface Problem {
  id: string;
  name: string;
  difficulty: "Easy" | "Medium" | "Hard";
  category: string;
  description: string;
  requirements: ProblemRequirements;
  constraints: string[];
  hints: string[];
  scoringCriteria: ScoringCriteria[];
}

export const PROBLEMS: Problem[] = [
  {
    id: "url-shortener",
    name: "URL Shortener",
    difficulty: "Easy",
    category: "Storage",
    description: "Design a service like bit.ly that shortens long URLs and redirects users.",
    requirements: { readsPerSec: 100, writesPerSec: 1, storage: "500 GB", latencySLA: "< 100ms", users: "100M DAU" },
    constraints: [
      "Short URLs must be unique and non-predictable (base62 or base58 encoding)",
      "Redirect latency < 100ms at p99",
      "System must handle 100:1 read/write ratio",
      "URLs should expire after a configurable TTL",
      "Custom aliases should be supported",
      "Analytics: track click counts per URL",
    ],
    hints: ["Start with the basics", "Think about the read path first", "A cache is critical for redirects", "Consider a dedicated ID generator for short codes"],
    scoringCriteria: [
      { description: "Traffic entry point (DNS/Load Balancer)", componentIds: ["dns", "load-balancer", "api-gateway"], points: 10 },
      { description: "Application layer to handle logic", componentIds: ["app-server"], points: 15 },
      { description: "Cache for hot URL lookups", componentIds: ["cache"], points: 20 },
      { description: "Persistent storage for URL mappings", componentIds: ["sql-db", "nosql-db"], points: 20 },
      { description: "ID generation for short codes", componentIds: ["id-generator"], points: 15 },
      { description: "CDN for static assets", componentIds: ["cdn"], points: 10 },
      { description: "Rate limiting to prevent abuse", componentIds: ["rate-limiter"], points: 10 },
    ],
  },
  {
    id: "twitter-feed",
    name: "Twitter / Social Feed",
    difficulty: "Hard",
    category: "Social",
    description: "Design Twitter's home timeline — generating and serving personalised feeds for millions of users.",
    requirements: { readsPerSec: 300, writesPerSec: 5, storage: "5 TB", latencySLA: "< 200ms", users: "300M DAU" },
    constraints: [
      "Fan-out on write vs fan-out on read trade-off",
      "Timeline must include tweets from all followed users",
      "Support up to 100M followers for celebrity accounts",
      "Tweets contain text, images, and videos",
      "Real-time notifications for new tweets",
    ],
    hints: ["Fan-out on write pre-computes timelines", "Celebrities need a hybrid approach", "Cache timelines in Redis", "Message queues handle async fan-out"],
    scoringCriteria: [
      { description: "Load balancing / API gateway", componentIds: ["load-balancer", "api-gateway"], points: 10 },
      { description: "Application servers", componentIds: ["app-server"], points: 10 },
      { description: "Timeline cache (Redis)", componentIds: ["cache"], points: 20 },
      { description: "Primary data store for tweets", componentIds: ["nosql-db", "sql-db"], points: 15 },
      { description: "Async fan-out with message queue", componentIds: ["message-queue", "pubsub"], points: 20 },
      { description: "CDN for media", componentIds: ["cdn", "object-storage"], points: 15 },
      { description: "Real-time notifications", componentIds: ["websocket-server", "notification-service"], points: 10 },
    ],
  },
  {
    id: "netflix",
    name: "Netflix / Video Streaming",
    difficulty: "Hard",
    category: "Media",
    description: "Design a video streaming platform that serves millions of concurrent viewers.",
    requirements: { readsPerSec: 500, writesPerSec: 0.1, storage: "100 PB", latencySLA: "< 50ms buffer start", users: "200M subscribers" },
    constraints: [
      "Video must be transcoded into multiple resolutions (360p–4K)",
      "Adaptive bitrate streaming (HLS/DASH)",
      "Global CDN with edge caching",
      "Upload pipeline for new content",
      "Recommendation engine",
    ],
    hints: ["CDN is the core of video delivery", "Transcode videos offline before serving", "Use object storage for video files", "Geolocation-based routing reduces latency"],
    scoringCriteria: [
      { description: "Global CDN for video delivery", componentIds: ["cdn"], points: 25 },
      { description: "Object storage for video files", componentIds: ["object-storage"], points: 20 },
      { description: "Load balancer for API traffic", componentIds: ["load-balancer"], points: 10 },
      { description: "Stream processing for transcode pipeline", componentIds: ["stream-processor", "message-queue"], points: 20 },
      { description: "Metadata database", componentIds: ["nosql-db", "sql-db"], points: 15 },
      { description: "Cache for metadata and user sessions", componentIds: ["cache"], points: 10 },
    ],
  },
  {
    id: "uber",
    name: "Uber / Ride Sharing",
    difficulty: "Hard",
    category: "Location",
    description: "Design Uber's backend — real-time driver matching, location tracking, and trip management.",
    requirements: { readsPerSec: 100, writesPerSec: 50, storage: "50 TB", latencySLA: "< 100ms", users: "100M DAU" },
    constraints: [
      "Driver location must update every 4 seconds",
      "Match rider to nearest available driver in < 1s",
      "Support geospatial queries for nearby drivers",
      "Surge pricing based on demand/supply",
      "Trip history and receipts",
    ],
    hints: ["Geospatial index is critical for nearby driver lookup", "WebSocket keeps driver location in sync", "Separate read (matching) from write (location update) paths"],
    scoringCriteria: [
      { description: "API gateway / load balancer", componentIds: ["api-gateway", "load-balancer"], points: 10 },
      { description: "WebSocket for real-time location", componentIds: ["websocket-server"], points: 20 },
      { description: "Geospatial index for driver lookup", componentIds: ["geospatial"], points: 25 },
      { description: "Cache for active driver sessions", componentIds: ["cache"], points: 15 },
      { description: "Trip and driver data store", componentIds: ["sql-db", "nosql-db"], points: 15 },
      { description: "Message queue for trip events", componentIds: ["message-queue", "pubsub"], points: 15 },
    ],
  },
  {
    id: "whatsapp",
    name: "WhatsApp / Messaging",
    difficulty: "Medium",
    category: "Messaging",
    description: "Design a real-time messaging system supporting 1-to-1 and group chats.",
    requirements: { readsPerSec: 100, writesPerSec: 100, storage: "10 TB", latencySLA: "< 100ms", users: "2B users" },
    constraints: [
      "Messages must be delivered in order",
      "Support offline delivery (message queuing)",
      "End-to-end encryption",
      "Group chats up to 1024 members",
      "Read receipts and typing indicators",
    ],
    hints: ["WebSockets for real-time delivery", "Message queues handle offline users", "NoSQL is better for message history", "Fanout for group messages"],
    scoringCriteria: [
      { description: "Load balancer / API gateway", componentIds: ["load-balancer", "api-gateway"], points: 10 },
      { description: "WebSocket servers for real-time", componentIds: ["websocket-server"], points: 25 },
      { description: "Message storage", componentIds: ["nosql-db"], points: 15 },
      { description: "Offline message queue", componentIds: ["message-queue"], points: 20 },
      { description: "Cache for online presence", componentIds: ["cache"], points: 15 },
      { description: "Notification service for offline", componentIds: ["notification-service"], points: 15 },
    ],
  },
  {
    id: "youtube",
    name: "YouTube / Video Platform",
    difficulty: "Hard",
    category: "Media",
    description: "Design YouTube — video upload, processing, storage, and serving at global scale.",
    requirements: { readsPerSec: 1000, writesPerSec: 0.5, storage: "1 PB", latencySLA: "< 100ms", users: "2B users" },
    constraints: [
      "500 hours of video uploaded per minute",
      "Support multiple video formats and resolutions",
      "Video search by title, description, tags",
      "Comment system with threading",
      "Like/dislike counts at high throughput",
    ],
    hints: ["Decouple upload from processing with a queue", "CDN is essential for video delivery", "Sharded counters for like counts", "Search needs an inverted index"],
    scoringCriteria: [
      { description: "CDN for video streaming", componentIds: ["cdn"], points: 20 },
      { description: "Object storage for video files", componentIds: ["object-storage"], points: 15 },
      { description: "Upload / processing pipeline", componentIds: ["message-queue", "stream-processor"], points: 20 },
      { description: "Search engine for video discovery", componentIds: ["search"], points: 15 },
      { description: "Sharded counters for views/likes", componentIds: ["sharded-counter"], points: 15 },
      { description: "Metadata database", componentIds: ["nosql-db", "sql-db"], points: 15 },
    ],
  },
  {
    id: "google-search",
    name: "Google Search",
    difficulty: "Hard",
    category: "Search",
    description: "Design a web search engine — crawling, indexing, and ranking billions of pages.",
    requirements: { readsPerSec: 5000, writesPerSec: 100, storage: "100 PB", latencySLA: "< 100ms", users: "1B DAU" },
    constraints: [
      "Crawl billions of pages continuously",
      "Build an inverted index for full-text search",
      "Rank results by relevance (PageRank + ML)",
      "Handle typos and synonyms",
      "Serve autocomplete suggestions in < 50ms",
    ],
    hints: ["Web crawler feeds a processing pipeline", "Inverted index stored in distributed storage", "Cache top queries aggressively", "Separate crawl, index, and serve tiers"],
    scoringCriteria: [
      { description: "Load balancer for search traffic", componentIds: ["load-balancer"], points: 10 },
      { description: "Search / inverted index", componentIds: ["search"], points: 25 },
      { description: "Cache for top search queries", componentIds: ["cache"], points: 20 },
      { description: "Data store for page metadata", componentIds: ["nosql-db", "data-warehouse"], points: 15 },
      { description: "Stream processing for index updates", componentIds: ["stream-processor", "message-queue"], points: 15 },
      { description: "CDN for serving search results", componentIds: ["cdn"], points: 15 },
    ],
  },
  {
    id: "instagram",
    name: "Instagram",
    difficulty: "Medium",
    category: "Social",
    description: "Design Instagram — photo/video upload, feed generation, and social graph.",
    requirements: { readsPerSec: 200, writesPerSec: 10, storage: "1 PB", latencySLA: "< 200ms", users: "500M DAU" },
    constraints: [
      "Images must be resized into multiple thumbnails",
      "Feed includes posts from followed accounts",
      "Stories expire after 24 hours",
      "Direct messages between users",
      "Explore page with personalised recommendations",
    ],
    hints: ["CDN serves media efficiently", "Pre-generate feeds for active users", "Separate storage for media vs metadata"],
    scoringCriteria: [
      { description: "CDN for photo/video delivery", componentIds: ["cdn"], points: 20 },
      { description: "Object storage for media", componentIds: ["object-storage"], points: 15 },
      { description: "Feed cache", componentIds: ["cache"], points: 20 },
      { description: "App servers for API", componentIds: ["app-server", "api-gateway"], points: 10 },
      { description: "Message queue for async processing", componentIds: ["message-queue", "pubsub"], points: 15 },
      { description: "Database for user and post data", componentIds: ["sql-db", "nosql-db"], points: 20 },
    ],
  },
  {
    id: "discord",
    name: "Discord / Chat",
    difficulty: "Medium",
    category: "Messaging",
    description: "Design Discord — real-time messaging with servers, channels, voice, and 150M users.",
    requirements: { readsPerSec: 50, writesPerSec: 50, storage: "5 TB", latencySLA: "< 50ms", users: "150M DAU" },
    constraints: [
      "Servers can have thousands of channels",
      "Messages must be delivered in order per channel",
      "Presence system showing who is online",
      "Voice/video channels via WebRTC",
      "Message history searchable",
    ],
    hints: ["WebSockets maintain presence state", "Scatter-gather pattern for reading channel history", "Time-series or NoSQL for message storage"],
    scoringCriteria: [
      { description: "WebSocket servers for real-time", componentIds: ["websocket-server"], points: 25 },
      { description: "Message store (time-ordered)", componentIds: ["nosql-db", "timeseries-db"], points: 20 },
      { description: "Cache for presence/channels", componentIds: ["cache"], points: 15 },
      { description: "Load balancer", componentIds: ["load-balancer"], points: 10 },
      { description: "Search for message history", componentIds: ["search"], points: 15 },
      { description: "Object storage for attachments", componentIds: ["object-storage"], points: 15 },
    ],
  },
  {
    id: "dropbox",
    name: "Dropbox / File Sync",
    difficulty: "Medium",
    category: "Storage",
    description: "Design Dropbox — file sync across devices with conflict resolution and sharing.",
    requirements: { readsPerSec: 50, writesPerSec: 10, storage: "100 TB", latencySLA: "< 500ms", users: "700M users" },
    constraints: [
      "Sync file changes across multiple devices",
      "Chunk large files for delta sync",
      "Handle concurrent edits (conflict resolution)",
      "Offline support — sync when reconnected",
      "Share files/folders with other users",
    ],
    hints: ["Split files into chunks and deduplicate", "Metadata server is separate from blob storage", "Message queue for async sync notifications"],
    scoringCriteria: [
      { description: "Object storage for file chunks", componentIds: ["object-storage"], points: 25 },
      { description: "Metadata database", componentIds: ["sql-db", "nosql-db"], points: 20 },
      { description: "Message queue for sync events", componentIds: ["message-queue"], points: 15 },
      { description: "Cache for metadata lookups", componentIds: ["cache"], points: 15 },
      { description: "CDN for file downloads", componentIds: ["cdn"], points: 15 },
      { description: "Load balancer", componentIds: ["load-balancer"], points: 10 },
    ],
  },
  {
    id: "rate-limiter",
    name: "API Rate Limiter",
    difficulty: "Easy",
    category: "Infrastructure",
    description: "Design a distributed rate limiter that can throttle API requests per user/IP.",
    requirements: { readsPerSec: 1000, writesPerSec: 1000, storage: "1 GB", latencySLA: "< 10ms", users: "N/A" },
    constraints: [
      "Token bucket or sliding window algorithm",
      "Works across multiple API gateway nodes",
      "Millisecond-level enforcement latency",
      "Support per-user, per-IP, and per-endpoint limits",
      "Graceful degradation if limiter is unavailable",
    ],
    hints: ["Redis atomic operations (INCR + EXPIRE) are the standard", "Centralised counter with local cache fallback", "Lua scripts prevent race conditions in Redis"],
    scoringCriteria: [
      { description: "API gateway as enforcement point", componentIds: ["api-gateway", "rate-limiter"], points: 25 },
      { description: "Cache/Redis for counters", componentIds: ["cache"], points: 35 },
      { description: "App server for rule evaluation", componentIds: ["app-server"], points: 20 },
      { description: "Config service for rate limit rules", componentIds: ["config-service"], points: 20 },
    ],
  },
  {
    id: "notification-system",
    name: "Notification System",
    difficulty: "Medium",
    category: "Messaging",
    description: "Design a push notification system that reliably delivers millions of alerts per second.",
    requirements: { readsPerSec: 10, writesPerSec: 100, storage: "1 TB", latencySLA: "< 1s", users: "1B users" },
    constraints: [
      "Support push (iOS/Android), email, and SMS",
      "Guaranteed at-least-once delivery",
      "Retry on failure with exponential backoff",
      "User notification preferences and opt-out",
      "Track delivery status per notification",
    ],
    hints: ["Fan-out through a message queue", "Dedicated handlers per channel (push vs email vs SMS)", "Store undelivered notifications for offline users"],
    scoringCriteria: [
      { description: "API for triggering notifications", componentIds: ["api-gateway", "app-server"], points: 15 },
      { description: "Message queue for async delivery", componentIds: ["message-queue", "pubsub"], points: 30 },
      { description: "Notification service per channel", componentIds: ["notification-service"], points: 25 },
      { description: "Database for preferences/history", componentIds: ["nosql-db", "sql-db"], points: 20 },
      { description: "Cache for user preferences", componentIds: ["cache"], points: 10 },
    ],
  },
  {
    id: "payment-system",
    name: "Payment System",
    difficulty: "Hard",
    category: "Finance",
    description: "Design a payment processing system that handles transactions safely at scale.",
    requirements: { readsPerSec: 10, writesPerSec: 10, storage: "10 TB", latencySLA: "< 200ms", users: "100M" },
    constraints: [
      "Exactly-once payment processing (idempotency)",
      "ACID transactions for fund transfers",
      "PCI-DSS compliance for card data",
      "Fraud detection in real time",
      "Reconciliation reports for auditing",
    ],
    hints: ["Idempotency keys prevent double charges", "Two-phase commit or Saga pattern for distributed transactions", "Message queue decouples payment initiation from processing"],
    scoringCriteria: [
      { description: "API gateway with auth", componentIds: ["api-gateway", "auth-service"], points: 15 },
      { description: "SQL database for ACID transactions", componentIds: ["sql-db"], points: 30 },
      { description: "Distributed lock for idempotency", componentIds: ["distributed-lock", "cache"], points: 20 },
      { description: "Message queue for async processing", componentIds: ["message-queue"], points: 20 },
      { description: "Monitoring / audit trail", componentIds: ["monitoring"], points: 15 },
    ],
  },
  {
    id: "web-crawler",
    name: "Web Crawler",
    difficulty: "Medium",
    category: "Search",
    description: "Design a distributed web crawler that indexes billions of pages.",
    requirements: { readsPerSec: 1, writesPerSec: 10, storage: "100 TB", latencySLA: "Best effort", users: "N/A" },
    constraints: [
      "Crawl 1 billion pages within a week",
      "Respect robots.txt and crawl delays",
      "Deduplication — don't re-crawl unchanged pages",
      "Prioritize important pages (high PageRank)",
      "Extract and store text, links, and metadata",
    ],
    hints: ["URL frontier is a priority queue", "DNS caching reduces lookup overhead", "Store raw HTML in object storage, index in search engine"],
    scoringCriteria: [
      { description: "Message queue as URL frontier", componentIds: ["message-queue", "pubsub"], points: 25 },
      { description: "Object storage for raw pages", componentIds: ["object-storage"], points: 20 },
      { description: "Search engine for indexing", componentIds: ["search"], points: 20 },
      { description: "Cache for DNS / dedup", componentIds: ["cache"], points: 15 },
      { description: "Stream processor for extraction", componentIds: ["stream-processor"], points: 20 },
    ],
  },
  {
    id: "google-maps",
    name: "Google Maps",
    difficulty: "Hard",
    category: "Location",
    description: "Design Google Maps — real-time traffic, routing, and location search.",
    requirements: { readsPerSec: 1000, writesPerSec: 10, storage: "100 TB", latencySLA: "< 100ms", users: "1B DAU" },
    constraints: [
      "Route calculation using Dijkstra or A*",
      "Real-time traffic updates every 30s",
      "Support walking, driving, and transit modes",
      "Render map tiles at multiple zoom levels",
      "Place search and Points of Interest",
    ],
    hints: ["Partition the world into tiles", "Graph database for road network", "CDN caches static map tiles", "Real-time traffic uses stream processing"],
    scoringCriteria: [
      { description: "CDN for map tile delivery", componentIds: ["cdn"], points: 20 },
      { description: "Geospatial index for location search", componentIds: ["geospatial"], points: 25 },
      { description: "Graph database for road network", componentIds: ["graph-db"], points: 20 },
      { description: "Stream processor for live traffic", componentIds: ["stream-processor", "pubsub"], points: 20 },
      { description: "Cache for popular routes", componentIds: ["cache"], points: 15 },
    ],
  },
  {
    id: "search-autocomplete",
    name: "Search Autocomplete",
    difficulty: "Medium",
    category: "Search",
    description: "Design a type-ahead search suggestion system like Google's autocomplete.",
    requirements: { readsPerSec: 1000, writesPerSec: 100, storage: "50 GB", latencySLA: "< 50ms", users: "1B users" },
    constraints: [
      "Return top-5 suggestions per prefix",
      "Update suggestions based on trending queries",
      "Support multiple languages",
      "Personalise suggestions per user",
    ],
    hints: ["Trie data structure stored in cache", "Pre-compute top queries per prefix offline", "Batch update the trie periodically"],
    scoringCriteria: [
      { description: "Cache for trie / prefix suggestions", componentIds: ["cache"], points: 35 },
      { description: "Search engine for full index", componentIds: ["search"], points: 20 },
      { description: "Load balancer", componentIds: ["load-balancer"], points: 10 },
      { description: "Stream processor for trending updates", componentIds: ["stream-processor", "message-queue"], points: 20 },
      { description: "Data store for query logs", componentIds: ["data-warehouse", "nosql-db"], points: 15 },
    ],
  },
  {
    id: "distributed-cache",
    name: "Distributed Cache (Redis)",
    difficulty: "Medium",
    category: "Infrastructure",
    description: "Design a distributed in-memory cache system like Redis.",
    requirements: { readsPerSec: 500, writesPerSec: 200, storage: "10 TB", latencySLA: "< 5ms", users: "N/A" },
    constraints: [
      "Consistent hashing for data distribution",
      "Replication for high availability",
      "Eviction policies (LRU, LFU, TTL)",
      "Atomic operations (INCR, SETNX)",
      "Persistence (AOF / RDB snapshots)",
    ],
    hints: ["Consistent hashing minimises key migration on node change", "Leader-follower replication for HA", "Async replication trades durability for performance"],
    scoringCriteria: [
      { description: "Load balancer for cache cluster", componentIds: ["load-balancer"], points: 15 },
      { description: "Cache nodes", componentIds: ["cache"], points: 30 },
      { description: "Coordination for cluster state", componentIds: ["coordination", "service-discovery"], points: 25 },
      { description: "Monitoring for eviction and hit rate", componentIds: ["monitoring"], points: 15 },
      { description: "Persistent backup store", componentIds: ["nosql-db", "object-storage"], points: 15 },
    ],
  },
  {
    id: "job-scheduler",
    name: "Distributed Job Scheduler",
    difficulty: "Medium",
    category: "Infrastructure",
    description: "Design a cron-like distributed job scheduler that reliably executes millions of tasks.",
    requirements: { readsPerSec: 100, writesPerSec: 10, storage: "1 TB", latencySLA: "< 100ms trigger delay", users: "N/A" },
    constraints: [
      "Exactly-once job execution",
      "Support cron expressions and one-off jobs",
      "Retry failed jobs with backoff",
      "Job dependency chains (DAGs)",
      "Dashboard to monitor job status",
    ],
    hints: ["Distributed lock prevents duplicate execution", "Message queue acts as the job queue", "Coordinator manages scheduling across workers"],
    scoringCriteria: [
      { description: "Message queue for job distribution", componentIds: ["message-queue"], points: 25 },
      { description: "Distributed lock for exactly-once", componentIds: ["distributed-lock"], points: 25 },
      { description: "App server / task scheduler", componentIds: ["task-scheduler", "app-server"], points: 20 },
      { description: "Database for job metadata", componentIds: ["sql-db", "nosql-db"], points: 15 },
      { description: "Monitoring / dashboard", componentIds: ["monitoring"], points: 15 },
    ],
  },
  {
    id: "stock-trading",
    name: "Stock Trading Platform",
    difficulty: "Hard",
    category: "Finance",
    description: "Design a stock exchange matching engine with real-time price feeds.",
    requirements: { readsPerSec: 500, writesPerSec: 100, storage: "10 TB", latencySLA: "< 10ms", users: "10M traders" },
    constraints: [
      "Order matching engine: price-time priority",
      "Order book must be consistent",
      "Real-time market data feed to clients",
      "Audit log for every transaction",
      "Circuit breakers for extreme volatility",
    ],
    hints: ["Single-threaded matching engine avoids locks", "Time-series DB for price history", "WebSockets push market data to clients", "Message queue buffers order flow"],
    scoringCriteria: [
      { description: "WebSocket for real-time market data", componentIds: ["websocket-server"], points: 20 },
      { description: "Message queue for order flow", componentIds: ["message-queue", "pubsub"], points: 20 },
      { description: "Time-series DB for price history", componentIds: ["timeseries-db"], points: 20 },
      { description: "SQL DB for orders / positions", componentIds: ["sql-db"], points: 20 },
      { description: "Cache for order book state", componentIds: ["cache"], points: 10 },
      { description: "Circuit breaker / monitoring", componentIds: ["circuit-breaker", "monitoring"], points: 10 },
    ],
  },
  {
    id: "collaborative-doc",
    name: "Google Docs (Collaborative Editor)",
    difficulty: "Hard",
    category: "Collaboration",
    description: "Design a real-time collaborative document editor like Google Docs.",
    requirements: { readsPerSec: 50, writesPerSec: 50, storage: "5 TB", latencySLA: "< 50ms", users: "1B users" },
    constraints: [
      "Concurrent edits must converge (OT or CRDT)",
      "Show other users' cursors in real time",
      "Persistent version history",
      "Offline editing with sync on reconnect",
      "Permissions: view / comment / edit",
    ],
    hints: ["Operational Transform (OT) or CRDT for conflict resolution", "WebSockets broadcast edits in real time", "Version history stored in append-only log"],
    scoringCriteria: [
      { description: "WebSocket for real-time collaboration", componentIds: ["websocket-server"], points: 25 },
      { description: "Document storage", componentIds: ["nosql-db", "object-storage"], points: 20 },
      { description: "Cache for active documents", componentIds: ["cache"], points: 15 },
      { description: "Message queue for operation broadcast", componentIds: ["pubsub", "message-queue"], points: 25 },
      { description: "Load balancer", componentIds: ["load-balancer"], points: 15 },
    ],
  },
];
